window.SENTENCES_AUDIO_MAP = {
  "Letter Bb. Sound b. Find the word that starts with Bb.": "assets/audios/sentences/frog_prompt_bb.mp3",
  "Letter Bb. Sound /b/. Find the word that starts with Bb.": "assets/audios/sentences/frog_prompt_bb.mp3",
  "Letter Bb. Find the word that starts with Bb": "assets/audios/sentences/frog_intro_bb.mp3",
  "Letter Tt. Sound t. Find the word that starts with Tt.": "assets/audios/sentences/frog_prompt_tt.mp3",
  "Letter Tt. Sound /t/. Find the word that starts with Tt.": "assets/audios/sentences/frog_prompt_tt.mp3",
  "Letter Tt. Find the word that starts with Tt": "assets/audios/sentences/frog_intro_tt.mp3",
  "Letter Mm. Sound m. Find the word that starts with Mm.": "assets/audios/sentences/frog_prompt_mm.mp3",
  "Letter Mm. Sound /m/. Find the word that starts with Mm.": "assets/audios/sentences/frog_prompt_mm.mp3",
  "Letter Mm. Find the word that starts with Mm": "assets/audios/sentences/frog_intro_mm.mp3",
  "Letter Ww. Sound w. Find the word that starts with Ww.": "assets/audios/sentences/frog_prompt_ww.mp3",
  "Letter Ww. Sound /w/. Find the word that starts with Ww.": "assets/audios/sentences/frog_prompt_ww.mp3",
  "Letter Ww. Find the word that starts with Ww": "assets/audios/sentences/frog_intro_ww.mp3",
  "What do I brush in the morning? Every morning, I wash my face and brush my teeth.": "assets/audios/sentences/frog_act_127f54a1.mp3",
  "Every morning, I wash my face and brush my teeth. What do I brush in the morning?": "assets/audios/sentences/frog_act_127f54a1.mp3",
  "What do I take to school? I eat delicious breakfast before I take the bus.": "assets/audios/sentences/frog_act_d0e1affe.mp3",
  "I eat delicious breakfast before I take the bus. What do I take to school?": "assets/audios/sentences/frog_act_d0e1affe.mp3",
  "What do I pack before sleep? Before I sleep, I pack my school bag.": "assets/audios/sentences/frog_act_db3ec649.mp3",
  "Before I sleep, I pack my school bag. What do I pack before sleep?": "assets/audios/sentences/frog_act_db3ec649.mp3",
  "Where do I sleep at night? This is my daily routine. I go to bed at night.": "assets/audios/sentences/frog_act_31948c6d.mp3",
  "This is my daily routine. I go to bed at night. Where do I sleep at night?": "assets/audios/sentences/frog_act_31948c6d.mp3",
  "What do I drink in the morning? In the morning, I drink a glass of fresh milk.": "assets/audios/sentences/frog_act_3f87c3a3.mp3",
  "In the morning, I drink a glass of fresh milk. What do I drink in the morning?": "assets/audios/sentences/frog_act_3f87c3a3.mp3"
};
